{"ID":4766,"Author":{"Name":"MhdSyrwan","ID":0,"FullName":"","Gravatar":"f0a7167202878b1ee71e3f388cc06277"},"Title":"Java Exceptions: Passing Exception Through Call Stack","Description":"\u003cdiv class=\"content\"\u003e\u003cp\u003eThis cast shows how exceptions are passed to the calling method if there\u0026#39;s no try-catch statement.\u003c/p\u003e\n\u003c/div\u003e","Time":"2013-08-15T02:07:31Z","Tags":["Linux","bash","xterm"]}